mod 'puppet/nginx'
mod 'puppetlabs/stdlib'
mod 'puppetlabs/concat'
mod 'pltraining/dockeragent'
#mod 'garethr/docker'
#mod 'garethr-docker', '5.3.0'
#mod 'pltraining-dockeragent', '0.0.16'
#mod 'puppetlabs-docker', '2.0.0'
mod 'puppetlabs-aws', '2.1.0'
